"""Evidence validation to ensure sources are real, not fabricated."""

from datetime import datetime, timedelta
from urllib.parse import urlparse
import re
from demand_research.models import SourceCard


class EvidenceValidator:
    """Validates that sources are real, dated, and properly attributed."""

    PLACEHOLDER_DOMAINS = {
        "example.com",
        "test.com",
        "fake.com",
        "mock.com",
        "placeholder.com",
    }

    def __init__(self, max_age_days: int = 365):
        self.max_age_days = max_age_days

    def validate_source(self, source: SourceCard) -> tuple[bool, list[str]]:
        """
        Validate a source card comprehensively.
        Returns: (is_valid, list_of_issues)
        """
        issues = []

        # Check URL validity
        url_issues = self._validate_url(str(source.url))
        issues.extend(url_issues)

        # Check date
        date_issues = self._validate_date(source.date_observed)
        issues.extend(date_issues)

        # Check price if provided
        if source.price_observed is not None:
            price_issues = self._validate_price(source.price_observed)
            issues.extend(price_issues)

        # Check buyer language if provided
        if source.buyer_language_captured:
            quote_issues = self._validate_quote(
                source.buyer_language_captured,
                source.is_direct_quote,
            )
            issues.extend(quote_issues)

        # Check source name is not generic
        if not source.source_name or len(source.source_name) < 3:
            issues.append("Source name is too short or missing")

        is_valid = len(issues) == 0
        return is_valid, issues

    def _validate_url(self, url: str) -> list[str]:
        """Validate URL is real and accessible."""
        issues = []

        if not url:
            issues.append("URL is missing")
            return issues

        # Check for placeholder domains
        parsed = urlparse(url)
        domain = parsed.netloc.lower()

        if any(placeholder in domain for placeholder in self.PLACEHOLDER_DOMAINS):
            issues.append(f"URL uses placeholder domain: {domain}")

        # Check URL format
        if not re.match(r"^https?://", url):
            issues.append("URL does not use http/https")

        # Check length (very short URLs are suspicious)
        if len(url) < 10:
            issues.append("URL is suspiciously short")

        return issues

    def _validate_date(self, date_observed: datetime) -> list[str]:
        """Validate date is recent and reasonable."""
        issues = []

        if not date_observed:
            issues.append("Date observed is missing")
            return issues

        # Check not in future
        if date_observed > datetime.utcnow():
            issues.append("Date observed is in the future")

        # Check not too old
        age_days = (datetime.utcnow() - date_observed).days
        if age_days > self.max_age_days:
            issues.append(f"Source is older than {self.max_age_days} days ({age_days} days old)")

        return issues

    def _validate_price(self, price: float) -> list[str]:
        """Validate price is realistic."""
        issues = []

        if price < 0:
            issues.append("Price is negative")

        if price == 0:
            issues.append("Price is zero (may be free product, but confirm)")

        # Check for unrealistic prices
        if price > 10000:
            issues.append("Price exceeds $10,000 (validate this is correct)")

        return issues

    def _validate_quote(self, quote: str, is_direct: bool = True) -> list[str]:
        """Validate buyer language quote."""
        issues = []

        if not quote or len(quote) < 5:
            issues.append("Quote is missing or too short")
            return issues

        # Check for AI-speak patterns (strong indicators of fabrication)
        ai_patterns = [
            r"\bas an AI\b",
            r"\bI am an AI\b",
            r"\bgenerated by\b",
            r"^This AI",
            r"^As an assistant",
            r"^I'm an AI",
            r"machine learning model",
        ]

        for pattern in ai_patterns:
            if re.search(pattern, quote, re.IGNORECASE):
                issues.append(f"Quote likely AI-generated (pattern: {pattern})")

        # Generic language patterns that suggest fabrication
        generic_patterns = [
            r"^this is a great",
            r"^overall, I think",
            r"^in conclusion",
            r"^in my opinion, this product",
        ]

        for pattern in generic_patterns:
            if re.search(pattern, quote, re.IGNORECASE):
                issues.append(f"Quote appears generic/templated (pattern: {pattern})")

        return issues

    # Positive-satisfaction phrases. A glowing review proves *satisfaction*, not
    # the target *pain* a buyer-language gate needs. These are matched only to
    # filter Phase 2 candidates more strictly — they never relax any gate.
    GENERIC_SATISFACTION_MARKERS = (
        "love it", "love this", "i love", "great product", "great purchase",
        "highly recommend", "works perfectly", "works great", "best purchase",
        "exactly what i needed", "exactly what i wanted", "worth every penny",
        "five stars", "5 stars", "so happy with", "amazing product", "perfect for",
        "thank you so much", "easy to use", "no complaints", "couldn't be happier",
        "would buy again", "absolutely love",
    )

    # Pain / unmet-need signals: even inside a positive review, these indicate a
    # real articulated problem and must NOT be filtered out as mere satisfaction.
    PAIN_SIGNAL_MARKERS = (
        "wish", "frustrat", "struggl", "hate", "annoying", "wasted", "waste of",
        "no sales", "not selling", "can't", "cant ", "couldn't figure", "too hard",
        "difficult", "confus", "overwhelm", "spent hours", "gave up", "doesn't",
        "does not", "missing", "lacks", "problem", "pain", "tired of", "sick of",
        "how do i", "how do you", "what do you use", "don't know what",
    )

    # Generic product-dissatisfaction phrases (broken file, rude seller, price,
    # aesthetics, vague dislike). A negative review made ONLY of these proves
    # dissatisfaction with a product, not the target buyer pain (deciding what
    # to make / validating demand before spending build time). Such quotes are
    # rejected durably — unless the exact quote also connects to the target job
    # (TARGET_JOB_MARKERS below). Stricter filter only: it can only reduce
    # accepted buyer language, never weaken any gate.
    GENERIC_NEGATIVE_MARKERS = (
        "bad download", "didn't open", "did not open", "won't open",
        "didn't work", "did not work", "doesn't work", "does not work",
        "stopped working", "seller was rude", "rude seller", "too expensive",
        "overpriced", "ugly", "not enough pages", "hard to use",
        "didn't like it", "did not like it", "don't like it", "poor quality",
        "low quality", "not worth it", "waste of money", "instructions unclear",
        "unclear instructions", "template broke", "couldn't access",
        "could not access", "can't access", "cannot access", "refund",
    )

    # Target-job/pain phrases for THIS primitive: deciding what digital product
    # to make, validating demand before build time, and the no-sales-after-
    # building pain. A negative review whose exact quote contains one of these
    # connects to the target job and may count as buyer-language evidence.
    TARGET_JOB_MARKERS = (
        "what to make", "what to build", "what to create", "what to sell",
        "what product", "which product", "what would sell", "what will sell",
        "what sells", "what customers want", "what buyers want",
        "no sales", "not selling", "zero sales", "nobody bought", "no one bought",
        "didn't sell", "did not sell", "doesn't sell", "never sold",
        "validate", "validation", "idea scoring", "product research",
        "decide what", "deciding what", "decide which", "help me decide",
        "too many ideas", "too many product ideas", "left me guessing",
        "still guessing", "before building", "before investing", "before i build",
        "build time", "spent hours making", "spent hours building",
        "wasted hours", "hours building", "hours making",
        "demand validation", "build or kill", "build-or-kill", "build/no-build",
    )

    def proves_target_pain(self, quote: str) -> bool:
        """True if the quote articulates an unmet need / pain (not just praise)."""
        low = (quote or "").lower()
        return any(marker in low for marker in self.PAIN_SIGNAL_MARKERS)

    def connects_to_target_job(self, quote: str) -> bool:
        """True if the exact quote ties to the target buyer job/pain themes."""
        low = (quote or "").lower()
        return any(marker in low for marker in self.TARGET_JOB_MARKERS)

    def is_generic_negative_review(self, quote: str) -> bool:
        """True if the quote is generic dissatisfaction unrelated to the target job.

        Negative does not automatically mean useful: "bad download", "seller was
        rude", or "too expensive" prove product dissatisfaction, not the target
        buyer pain. Such quotes are rejected to the durable rejected-source log
        (still useful audit evidence — they show the system did not cherry-pick).
        A negative review is kept when its exact words connect to the target job
        ("didn't help me know what product to make", "still got no sales").
        """
        low = (quote or "").strip().lower()
        if not low:
            return False
        if self.connects_to_target_job(low):
            return False  # negative AND on-target — genuine buyer-pain candidate
        return any(marker in low for marker in self.GENERIC_NEGATIVE_MARKERS)

    def is_generic_satisfaction_quote(self, quote: str) -> bool:
        """True if the quote is generic satisfaction/praise with no articulated pain.

        A satisfied-customer quote ("love it, works perfectly") proves the
        category sells, but it does NOT prove the target buyer pain a Phase 2
        buyer-language artifact must demonstrate. Such quotes are rejected to the
        durable rejected-source log rather than counted as pain evidence. This is
        a stricter filter; it can only reduce accepted buyer language, never
        weaken any gate.
        """
        low = (quote or "").strip().lower()
        if not low:
            return False
        if self.proves_target_pain(low):
            return False  # an articulated pain/unmet need — keep it
        return any(marker in low for marker in self.GENERIC_SATISFACTION_MARKERS)

    def validate_batch(self, sources: list[SourceCard]) -> tuple[list[SourceCard], list[tuple[SourceCard, list[str]]]]:
        """
        Validate a batch of sources.
        Returns: (valid_sources, invalid_sources_with_issues)
        """
        valid = []
        invalid = []

        for source in sources:
            is_valid, issues = self.validate_source(source)
            if is_valid:
                valid.append(source)
            else:
                invalid.append((source, issues))

        return valid, invalid
