"""Evidence validation to ensure sources are real, not fabricated."""

from datetime import datetime, timedelta
from urllib.parse import urlparse
import re
from demand_research.models import SourceCard


class EvidenceValidator:
    """Validates that sources are real, dated, and properly attributed."""

    PLACEHOLDER_DOMAINS = {
        "example.com",
        "test.com",
        "fake.com",
        "mock.com",
        "placeholder.com",
    }

    def __init__(self, max_age_days: int = 365):
        self.max_age_days = max_age_days

    def validate_source(self, source: SourceCard) -> tuple[bool, list[str]]:
        """
        Validate a source card comprehensively.
        Returns: (is_valid, list_of_issues)
        """
        issues = []

        # Check URL validity
        url_issues = self._validate_url(str(source.url))
        issues.extend(url_issues)

        # Check date
        date_issues = self._validate_date(source.date_observed)
        issues.extend(date_issues)

        # Check price if provided
        if source.price_observed is not None:
            price_issues = self._validate_price(source.price_observed)
            issues.extend(price_issues)

        # Check buyer language if provided
        if source.buyer_language_captured:
            quote_issues = self._validate_quote(
                source.buyer_language_captured,
                source.is_direct_quote,
            )
            issues.extend(quote_issues)

        # Check source name is not generic
        if not source.source_name or len(source.source_name) < 3:
            issues.append("Source name is too short or missing")

        is_valid = len(issues) == 0
        return is_valid, issues

    def _validate_url(self, url: str) -> list[str]:
        """Validate URL is real and accessible."""
        issues = []

        if not url:
            issues.append("URL is missing")
            return issues

        # Check for placeholder domains
        parsed = urlparse(url)
        domain = parsed.netloc.lower()

        if any(placeholder in domain for placeholder in self.PLACEHOLDER_DOMAINS):
            issues.append(f"URL uses placeholder domain: {domain}")

        # Check URL format
        if not re.match(r"^https?://", url):
            issues.append("URL does not use http/https")

        # Check length (very short URLs are suspicious)
        if len(url) < 10:
            issues.append("URL is suspiciously short")

        return issues

    def _validate_date(self, date_observed: datetime) -> list[str]:
        """Validate date is recent and reasonable."""
        issues = []

        if not date_observed:
            issues.append("Date observed is missing")
            return issues

        # Check not in future
        if date_observed > datetime.utcnow():
            issues.append("Date observed is in the future")

        # Check not too old
        age_days = (datetime.utcnow() - date_observed).days
        if age_days > self.max_age_days:
            issues.append(f"Source is older than {self.max_age_days} days ({age_days} days old)")

        return issues

    def _validate_price(self, price: float) -> list[str]:
        """Validate price is realistic."""
        issues = []

        if price < 0:
            issues.append("Price is negative")

        if price == 0:
            issues.append("Price is zero (may be free product, but confirm)")

        # Check for unrealistic prices
        if price > 10000:
            issues.append("Price exceeds $10,000 (validate this is correct)")

        return issues

    def _validate_quote(self, quote: str, is_direct: bool = True) -> list[str]:
        """Validate buyer language quote."""
        issues = []

        if not quote or len(quote) < 5:
            issues.append("Quote is missing or too short")
            return issues

        # Check for AI-speak patterns (strong indicators of fabrication)
        ai_patterns = [
            r"\bas an AI\b",
            r"\bI am an AI\b",
            r"\bgenerated by\b",
            r"^This AI",
            r"^As an assistant",
            r"^I'm an AI",
            r"machine learning model",
        ]

        for pattern in ai_patterns:
            if re.search(pattern, quote, re.IGNORECASE):
                issues.append(f"Quote likely AI-generated (pattern: {pattern})")

        # Generic language patterns that suggest fabrication
        generic_patterns = [
            r"^this is a great",
            r"^overall, I think",
            r"^in conclusion",
            r"^in my opinion, this product",
        ]

        for pattern in generic_patterns:
            if re.search(pattern, quote, re.IGNORECASE):
                issues.append(f"Quote appears generic/templated (pattern: {pattern})")

        return issues

    def validate_batch(self, sources: list[SourceCard]) -> tuple[list[SourceCard], list[tuple[SourceCard, list[str]]]]:
        """
        Validate a batch of sources.
        Returns: (valid_sources, invalid_sources_with_issues)
        """
        valid = []
        invalid = []

        for source in sources:
            is_valid, issues = self.validate_source(source)
            if is_valid:
                valid.append(source)
            else:
                invalid.append((source, issues))

        return valid, invalid
